name = "Base with emoji themed Polybar"
extends = "base"

[custom.polybar]
modules_left = "i3"
modules_center = ""
modules_right = "eth wifi cpu memory volume batteryemoji time date xkeyboard"
text_offset = "2"
icon_font_scale ="8"
antialias = "true"
bottom = "false"
height = "32"
i3_label = "%icon%"
wifi_dev = "wlp3s0"
wifi_icon = "ğŸ“¡"
eth_dev = "enp2s0"
eth_icon = "ğŸ”Œ"
cpu_icon = "ğŸ’»"
ram_icon = "ğŸ§ "
date_icon = "ğŸ“…"
time_icon = "ğŸ•–"
volume_icon = "ğŸ”Š"
mute_icon = "ğŸ”ˆ"
layout_icon = "âŒ¨ï¸"
charging_icon = "ğŸ”‹â¬†ï¸"
full_charge_icon = "ğŸ”‹"
discharging_icon = "ğŸ”‹â¬‡ï¸"

